### ISSUE TITLE
cartridge-add fails

### ISSUE THREAD

**Issue by trampgeek** [Praisebetoscience/openshift-cartridge-python-3.5#4]
Hi
Many thanks for making this cartridge available. It seems to be exactly what I'm looking for. Unfortunately, though, I don't seem to be able to add it to my PHP-5.4 Openshift app. I've tried the web ui and rhc and both fail in the same way.

With rhc I create a new app 

$ rhc app-create myapp php-5.4

then I cd into the newly-created git repository and type the command

$ rhc cartridge-add http://cartreflect-claytondev.rhcloud.com/github/Praisebetoscience/openshift-cartridge-python-3.5

There's a delay of a couple of minutes, then a huge log file is dumped to the screen, with the last few lines being

/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:604: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:606: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:589: warning: will never be executed
/bin/sh: line 4: cd:
/var/lib/openshift/56b31f0b7628e160300000b9/python/usr/lib/pkgconfig: No such file or directory
/bin/sh: line 0: cd:
/var/lib/openshift/56b31f0b7628e160300000b9/python/usr/lib/pkgconfig: No such file or directory
/var/lib/openshift/56b31f0b7628e160300000b9/python/bin/install: line 59:
/var/lib/openshift/56b31f0b7628e160300000b9/python//usr/bin/python: No such file or directory

The errors occur during the install of python-3.5; earlier installs, such as pip, seemed to be OK.

If I attempt to repeat the cartridge-add command (or try again to add the cartridge via the web UI), I get an error like:

Shell command '/sbin/runuser -s /bin/sh 56b31f0b7628e160300000b9 -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c5,c742' /bin/sh -c \"/var/lib/openshift/56b31f0b7628e160300000b9/python/bin/install --version 3.5.0\""' returned an error. rc=33
Installing Python 3.5.0
** Resuming transfer from byte position 20053428
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0 19.1M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

What am I doing wrong?

-- Richard

**Comment by johanson** [comment]
rhc cartridge-add <dbcartridge> --app <myappname>

<dbcartridge> - http://cartreflect-claytondev.rhcloud.com/github/Praisebetoscience/openshift-cartridge-python-3.5

**Comment by Grief** [comment]
@johanson Yes, I did exactly the same and I have the same issue

**Comment by johanson** [comment]
What if you try to do it all from the UI web backend? Still same?

**Comment by Grief** [comment]
@johanson Yes it is. But at the moment I have your repo forked and after some commeting in and out, I would say the following:
1. `-C -` option must be excluded from curl command since `www.python.org` doesn't support byte ranges and this cause reinstall to fail. This is metnioned by @trampgeek in the end of his message.
2. When I tried to install cartridge from forked repo, I've faced different issue somewhy. But the only change I did is the installation from raw version of manifest.yml. Not sure why, but I was failing on almost every command with the following stacktrace in `rhc`: 

```
/usr/lib/ruby/2.1.0/erb.rb:850:in `eval': (erb):1: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '(' (SyntaxError)
...    % Received % Xferd  Average Speed   Time    Time     Tim...
...                               ^
        from /usr/lib/ruby/2.1.0/erb.rb:850:in `result'
        from /usr/lib/ruby/vendor_ruby/rhc/highline_extensions.rb:48:in `say'
        from /usr/lib/ruby/vendor_ruby/rhc/helpers.rb:319:in `error'
        from /usr/lib/ruby/vendor_ruby/rhc/command_runner.rb:96:in `rescue in run!'
        from /usr/lib/ruby/vendor_ruby/rhc/command_runner.rb:71:in `run!'
        from /usr/lib/ruby/vendor_ruby/commander/delegates.rb:15:in `run!'
        from /usr/lib/ruby/vendor_ruby/rhc/cli.rb:37:in `start'
        from /usr/bin/rhc:20:in `<main>'
```

So, as I don't know Ruby at all, I decided simly route output of commands to `>/dev/null`. That made me able to install python without pip and virtualenv which are not installed, but I don't need them so I stopped at that point.

**Comment by johanson** [comment]
@Grief It's not my repo. I just happened to be here since I found this repo today and it worked well for my needs. And no errors as described by you.

I try to create a new cartridge again and see if it fails somewhere. I'll let you know later.

**Comment by Grief** [comment]
@johanson sorrrry for confusion. And thanks for you help! BTW I use free small gear, not sure if it matters

**Comment by johanson** [comment]
@Grief 

I have the same problem and error now. I tried different zones, but it doesn't matter.

I need to set up more cartridges so I'm looking for a solution too.

**Comment by johanson** [comment]
Here's the answer to the problem, so it's safe to close this issue: https://github.com/openshift/sti-python/issues/75#issuecomment-188372345

**Comment by Grief** [comment]
@johanson now sure that this can be called an 'answer' as it still in progress. If you want 3.5 now, could you please try to install it from my fork? pip and virtual env are not installed, but you can install them manually via ssh later.

**Comment by johanson** [comment]
@Grief Well, since the author of this repo made the cartridge for another purpose, I believe it is closed, it's really irrelevant now. We can move the discussion under your repo. :+1: 

I'll give a try soon, thanks.

**Comment by YAmikep** [comment]
I have the same issue:

```
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c: In function 'ffi_closure_unix64_inner':
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:627: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:328: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:333: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:346: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:618: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:604: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:606: warning: will never be executed
/tmp/python-3.5.0/Modules/_ctypes/libffi/src/x86/ffi64.c:589: warning: will never be executed
/bin/sh: line 4: cd: /var/lib/openshift/56d8eb072d5271913d000016/python/usr/lib/pkgconfig: No such file or directory
/bin/sh: line 0: cd: /var/lib/openshift/56d8eb072d5271913d000016/python/usr/lib/pkgconfig: No such file or directory
/var/lib/openshift/56d8eb072d5271913d000016/python/bin/install: line 59: /var/lib/openshift/56d8eb072d5271913d000016/python//usr/bin/python: No such file or directory
```

I created a cartridge using Do-It-Yourself 0.1 and then did:
`rhc cartridge-add http://cartreflect-claytondev.rhcloud.com/github/Praisebetoscience/openshift-cartridge-python-3.5 --app <myappname>`

Was anybody able to get python 3.5 on a cartridge?

Thanks

**Comment by Grief** [comment]
@YAmikep did you try my fork? It installs python only (no virtual env or pip) though. But pip can be installed manually later with `wget https://bootstrap.pypa.io/get-pip.py; python3.5 get-pip.py`

**Comment by YAmikep** [comment]
@Grief Just tried it, thanks it works.

I think I found the code for the official python cartridges under:
https://github.com/openshift/origin-server/tree/master/cartridges/openshift-origin-cartridge-python

I'm wondering whether reusing this template and changing it for python3.5 would be overall easier than starting from scratch to create the cartridge.

I guess it'd be even better if Openshift Online move to Openshift v3 since they are working on supporting python 3.5.

**Comment by Grief** [comment]
Hi @YAmikep. I don't think that it is possible to reuse the code from that repository. I am not sure for 100% but I believe that it uses pythons 2.7 and 3.3 which are already installed there outside of the gears' environments. I mean I am not sure how it works so it's just a guess, but I would say that it just makes symlinks or copies files into home directory or something like that. At least I had such impression while looked through the source code. this cartridge, in contrary, downloads python src from python.org, compiles it and sets up the environment. This is the reason why it takes so long to install it.

Regarding openshift online, you, probably, already saw that it will be updated with docker-based v3 in weeks or maybe even monthes. For myself, I decided to use this cartridge until that date because I am using it for hosting of a pet project, not a serious app, so it will not cost me money if something bad would happen. If you are at development/testing stage and you need python3.5 now, you can use it too and replace it with the official python3.5 image when it will arrive. There is no option for hosting python3.5 based apps in production at the moment.

**Comment by trampgeek** [comment]
@Grief I tried using your fork and it works beautifully. I don't need pip, so my problem is solved. Many thanks.

**Comment by YAmikep** [comment]
@Grief Agreed, good enough for now. Thanks.

**Comment by quangv** [comment]
I just wanted to add I also couldn't use this cartridge, it gave me similar error msgs. "/var/lib/openshift/56b31f0b7628e160300000b9/python//usr/bin/python: No such file or directory"

I was able to use @Grief branch though with command:

`rhc app create <app-name> https://raw.githubusercontent.com/Grief/openshift-cartridge-python-3.5/master/metadata/manifest.yml diy-0.1`

Thanks guys for these custom cartridges!

**Comment by Grief** [comment]
@quangv: Nice installation one-liner. I've merged your changes.

**Comment by Sikksens** [comment]
Is there a way to install app requirements, I keep getting Permission Denied on certain dependencies.
